### ISSUE TITLE
No way to use web-ifc-three with latest threejs version or any version other then 0.135.0

### ISSUE THREAD

**Issue by brutestack** [IFCjs/web-ifc-three#115]
Since this commit 852970e1137c9b1bdf189b4fe7deaf785408d47f there is no way to use web-ifc-three with any version of threejs other then 0.135.0 because of exact version match requirement in peerDependencies part of package.json
![image](https://user-images.githubusercontent.com/2864137/178360174-a61ba1c3-0540-4799-b461-8ca4bfba9a0c.png)

Is it really important for web-ifc-three to be used exactly with threejs version 0.135.0?

**Comment by HassanEmam** [comment]
You can build the package on your local machine and update dependency to Three.js version you need and use it in your project. I have tested it and it did work.

**Comment by makc** [comment]
@brutestack there is always a [way](https://stackoverflow.com/a/70396201/1652613) ;)

**Comment by aka-blackboots** [comment]
@brutestack, I hope the fix by @makc worked. Let us know if it still does not work.

**Comment by agviegas** [comment]
Hey, I just published a new version that uses 0.149.0! If neither this nor the solutions above solve your issue, let us know. Otherwise, we'll eventually close this issue.

**Comment by DoisKoh** [comment]
This is still an issue, and the problem is that ThreeJS versions start at 0.X.X. It's probably better to just remove three as a peerDepedency until ThreeJS decides to increment the Major.

**Comment by makc** [comment]
> until ThreeJS decides to increment the Major

which is likely never

**Comment by agviegas** [comment]
@DoisKoh how would you like to find the dependency in the library? 🤔

**Comment by DoisKoh** [comment]
Unfortunately I can't think of a solution outside of stating clearly in the documentation what version of ThreeJS is supported - as it stands right now, without manually modifying the `package-lock.json`, we can't install `web-ifc-three` due to the conflict in the peerDepedency version of ThreeJS and the actual newer versions of ThreeJS (because of npm's semver rules for anything below 0.X.X).
